language: python

os: linux

dist: bionic

python:
  - "3.6.10"
  - "3.7.7"
  - "3.8.2"
  
snaps:
- name: snapcraft
  classic: true
  channel: stable

jobs:
  fast_finish: true

install:
  - pip install -r requirements.txt

script: python3 setup.py install
