language: python

os: linux

dist: xenial

python:
  - "3.6.10"
  - "3.7.7"
  - "3.8.2"

addons:
  snaps:
  - name: snapcraft
    confinement: classic
    channel: stable

jobs:
  fast_finish: true

install:
  - pip install -r requirements.txt
  - pip check
  - python3 setup.py install
  - pip check
  - krop --version
  - pip uninstall -y krop
  
before-script:
  - snapcraft

script: krop --version
