language: python

os: linux

dist: bionic

python:
  - "3.6.10"
  - "3.7.7"
  - "3.8.2"

jobs:
  fast_finish: true
  include:
    language: shell
    os: linux
    dist: xenial
    addons:
      snaps:
        name: snapcraft
        channel: latest/stable
        confinement: classic
    before_install: 
      - sudo apt-get install --yes qtbase5-dev
    install: snapcraft
    
install:
  - pip install -r requirements.txt
  - pip check
  - python3 setup.py install
  
script: krop --version
