language: python

os: linux

dist: bionic

python:
  - "3.6.10"
  - "3.7.7"
  - "3.8.2"

addons:
  snaps:
  - name: snapcraft
    confinement: classic
    channel: stable

jobs:
  fast_finish: true

before-install:
  - pip install -r requirements.txt
  - python3 setup.py install
  - pip uninstall krop

install:
  - snapcraft

script: krop --version
