name:               krop
version:            0.5.1
summary:            A tool to crop PDF files
description:        |
  krop is a simple graphical tool to crop the pages of PDF files.
  It is written in Python and relies on PyQT, python-poppler-qt and pyPDF for
  its functionality. A unique feature of krop is its ability to automatically
  split pages into subpages to fit the limited screen size of devices such as
  eReaders. This is particularly useful, if your eReader does not support
  convenient scrolling.

grade:              stable
confinement:        strict
type:               app
base:               core18

apps:
  krop:
    command:        desktop-launch krop
    extensions: 
      - kde-neon
    command-chain:
      - snap/command-chain/snapcraft-runner
    environment:
      HOME: $SNAP_USER_COMMON
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - home
      - removable-media
      - browser-support
      - x11
      - gsettings

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  kde-frameworks-5-plug:
    interface: content
    target: kf5
    default-provider: kde-frameworks-5-core18:kde-frameworks-5-core18-slot
    
parts:      
  krop-app:
    source: https://github.com/arminstraub/krop/archive/v$SNAPCRAFT_PROJECT_VERSION.tar.gz   
    plugin:       python
    python-version: python3
    stage-packages:
      - python3-sip
      - python3-poppler-qt5
      - python3-pypdf2
      - python3-pyqt5 # needed
      - appmenu-qt
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - xdg-utils  # https://www.freedesktop.org/wiki/Software/xdg-utils/
      - libgail-common
      - libatk-adaptor
      - unity-gtk-module-common
