name: Release Drafter

on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    
    - name: Build Snap
      run: snapcraft
    
    - uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
